language: node_js
node_js:
  - "stable"
# cache:
#   directories:
#   - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
# before_script:
  # - "npm i -g gh-pages"
#   - "npm i -g gatsby"
#   - "npm i"
script:
  - "npm run test"
  - "npm run build"

before_deploy:
  - cd public  
# after_success:
  # - "npm run deploy:gh-pages"
